### ISSUE TITLE
Left sidebar max. 30% of Screen-width, but no more than 400 px

### ISSUE THREAD

**Issue by navid-kalaei** [kartevonmorgen/kartevonmorgen.ts#114] opened 2022-04-24 01:38 UTC
https://github.com/kartevonmorgen/kartevonmorgen/issues/770

**Comment by wellemut** [comment] 2022-04-25 13:38
duplicate
Duplicate of #https://github.com/kartevonmorgen/kartevonmorgen/issues/770

**Closed** 2022-04-25 13:38 UTC
